import type { ETFDefinition } from "../types";

export const ETF_UNIVERSE: ETFDefinition[] = [
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    category: "BROAD_MARKET",
    theme: "S&P 500 / US Core Large Cap",
    description: "Referência primária do mercado acionário norte-americano (500 maiores empresas dos EUA).",
    expenseRatioPct: 0.09,
    aumBillionsUSD: 560.5,
    inceptionDate: "1993-01-22",
    holdingsCount: 503,
    topHoldingsConcentrationPct: 32.5,
    topHoldings: [
      { symbol: "MSFT", name: "Microsoft Corp.", weightPct: 7.1 },
      { symbol: "AAPL", name: "Apple Inc.", weightPct: 6.8 },
      { symbol: "NVDA", name: "NVIDIA Corp.", weightPct: 6.4 },
      { symbol: "AMZN", name: "Amazon.com Inc.", weightPct: 3.7 },
      { symbol: "META", name: "Meta Platforms Inc.", weightPct: 2.5 },
    ],
  },
  {
    ticker: "QQQ",
    name: "Invesco QQQ Trust (Nasdaq-100)",
    category: "TECH_SEMIS",
    theme: "Nasdaq / Mega Cap Technology",
    description: "Exposição concentrada no índice Nasdaq-100, focado nas maiores líderes de tecnologia e inovação.",
    expenseRatioPct: 0.20,
    aumBillionsUSD: 285.4,
    inceptionDate: "1999-03-10",
    holdingsCount: 101,
    topHoldingsConcentrationPct: 48.2,
    topHoldings: [
      { symbol: "AAPL", name: "Apple Inc.", weightPct: 8.9 },
      { symbol: "MSFT", name: "Microsoft Corp.", weightPct: 8.4 },
      { symbol: "NVDA", name: "NVIDIA Corp.", weightPct: 7.8 },
      { symbol: "AMZN", name: "Amazon.com Inc.", weightPct: 5.1 },
      { symbol: "AVGO", name: "Broadcom Inc.", weightPct: 4.6 },
    ],
  },
  {
    ticker: "AIQ",
    name: "Global X Artificial Intelligence & Tech ETF",
    category: "AI_AUTOMATION",
    theme: "Inteligência Artificial & Robótica",
    description: "Investe em empresas desenvolvendo hardware, software e aplicações de Inteligência Artificial generativa.",
    expenseRatioPct: 0.68,
    aumBillionsUSD: 2.4,
    inceptionDate: "2018-05-11",
    holdingsCount: 84,
    topHoldingsConcentrationPct: 27.8,
    topHoldings: [
      { symbol: "NVDA", name: "NVIDIA Corp.", weightPct: 3.8 },
      { symbol: "ORCL", name: "Oracle Corp.", weightPct: 3.5 },
      { symbol: "TCEHY", name: "Tencent Holdings Ltd.", weightPct: 3.4 },
      { symbol: "META", name: "Meta Platforms Inc.", weightPct: 3.3 },
      { symbol: "NOW", name: "ServiceNow Inc.", weightPct: 3.2 },
    ],
  },
  {
    ticker: "SOXX",
    name: "iShares Semiconductor ETF",
    category: "TECH_SEMIS",
    theme: "Semicondutores & Processadores",
    description: "Proporciona exposição direta aos fabricantes globais de chips, GPUs e infraestrutura de hardware.",
    expenseRatioPct: 0.35,
    aumBillionsUSD: 14.8,
    inceptionDate: "2001-07-10",
    holdingsCount: 30,
    topHoldingsConcentrationPct: 56.4,
    topHoldings: [
      { symbol: "NVDA", name: "NVIDIA Corp.", weightPct: 8.9 },
      { symbol: "AVGO", name: "Broadcom Inc.", weightPct: 8.2 },
      { symbol: "AMD", name: "Advanced Micro Devices", weightPct: 7.4 },
      { symbol: "QCOM", name: "QUALCOMM Inc.", weightPct: 6.8 },
      { symbol: "TXN", name: "Texas Instruments Inc.", weightPct: 5.5 },
    ],
  },
  {
    ticker: "SMH",
    name: "VanEck Semiconductor ETF",
    category: "TECH_SEMIS",
    theme: "Líderes Globais de Semicondutores",
    description: "Provedor líder com alta concentração na TSMC e NVIDIA, coração da cadeia global de chips.",
    expenseRatioPct: 0.35,
    aumBillionsUSD: 22.1,
    inceptionDate: "2011-12-20",
    holdingsCount: 26,
    topHoldingsConcentrationPct: 62.1,
    topHoldings: [
      { symbol: "NVDA", name: "NVIDIA Corp.", weightPct: 20.4 },
      { symbol: "TSM", name: "Taiwan Semiconductor (TSMC)", weightPct: 12.8 },
      { symbol: "AVGO", name: "Broadcom Inc.", weightPct: 7.9 },
      { symbol: "ASML", name: "ASML Holding NV", weightPct: 5.4 },
      { symbol: "AMD", name: "Advanced Micro Devices", weightPct: 4.8 },
    ],
  },
  {
    ticker: "XLE",
    name: "Energy Select Sector SPDR Fund",
    category: "ENERGY_NUCLEAR",
    theme: "Energia Tradicional & Petróleo",
    description: "Exposição direta às gigantes de petróleo, gás natural e refino (ExxonMobil, Chevron).",
    expenseRatioPct: 0.09,
    aumBillionsUSD: 37.2,
    inceptionDate: "1998-12-16",
    holdingsCount: 23,
    topHoldingsConcentrationPct: 58.9,
    topHoldings: [
      { symbol: "XOM", name: "Exxon Mobil Corp.", weightPct: 22.8 },
      { symbol: "CVX", name: "Chevron Corp.", weightPct: 15.4 },
      { symbol: "COP", name: "ConocoPhillips", weightPct: 8.2 },
      { symbol: "EOG", name: "EOG Resources Inc.", weightPct: 4.9 },
      { symbol: "SLB", name: "Schlumberger Ltd.", weightPct: 4.6 },
    ],
  },
  {
    ticker: "URA",
    name: "Global X Uranium ETF",
    category: "ENERGY_NUCLEAR",
    theme: "Urânio & Energia Nuclear",
    description: "Investe na cadeia de mineração de urânio e componentes para reatores de energia nuclear limpa.",
    expenseRatioPct: 0.69,
    aumBillionsUSD: 3.1,
    inceptionDate: "2010-11-04",
    holdingsCount: 46,
    topHoldingsConcentrationPct: 44.5,
    topHoldings: [
      { symbol: "CCJ", name: "Cameco Corp.", weightPct: 23.4 },
      { symbol: "KAP", name: "Kazatomprom Kazatomprom", weightPct: 8.9 },
      { symbol: "SMR", name: "NuScale Power Corp.", weightPct: 4.5 },
      { symbol: "BWXT", name: "BWX Technologies Inc.", weightPct: 4.1 },
      { symbol: "NXE", name: "NexGen Energy Ltd.", weightPct: 3.8 },
    ],
  },
  {
    ticker: "COPX",
    name: "Global X Copper Miners ETF",
    category: "INFRA_MATERIALS",
    theme: "Mineração de Cobre & Transição Energética",
    description: "Foco nas maiores mineradoras de cobre do mundo, metal essencial para veículos elétricos e data centers.",
    expenseRatioPct: 0.65,
    aumBillionsUSD: 2.1,
    inceptionDate: "2010-04-19",
    holdingsCount: 41,
    topHoldingsConcentrationPct: 31.2,
    topHoldings: [
      { symbol: "FCX", name: "Freeport-McMoRan Inc.", weightPct: 5.6 },
      { symbol: "BHP", name: "BHP Group Ltd.", weightPct: 5.4 },
      { symbol: "RIO", name: "Rio Tinto PLC", weightPct: 5.2 },
      { symbol: "LUN", name: "Lundin Mining Corp.", weightPct: 4.8 },
      { symbol: "CS", name: "Capstone Copper Corp.", weightPct: 4.5 },
    ],
  },
  {
    ticker: "PAVE",
    name: "Global X U.S. Infrastructure Development ETF",
    category: "INFRA_MATERIALS",
    theme: "Infraestrutura & Reindustrialização dos EUA",
    description: "Empresas envolvidas na construção, pontes, rodovias e modernização industrial da América do Norte.",
    expenseRatioPct: 0.47,
    aumBillionsUSD: 7.4,
    inceptionDate: "2017-03-06",
    holdingsCount: 101,
    topHoldingsConcentrationPct: 22.4,
    topHoldings: [
      { symbol: "TRGP", name: "Targa Resources Corp.", weightPct: 3.4 },
      { symbol: "ETN", name: "Eaton Corp. PLC", weightPct: 3.2 },
      { symbol: "URI", name: "United Rentals Inc.", weightPct: 3.1 },
      { symbol: "EMR", name: "Emerson Electric Co.", weightPct: 3.0 },
      { symbol: "PWR", name: "Quanta Services Inc.", weightPct: 2.9 },
    ],
  },
  {
    ticker: "IHAK",
    name: "iShares Cybersecurity and Tech ETF",
    category: "CYBERSECURITY",
    theme: "Cibersegurança & Proteção de Dados",
    description: "Empresas líderes em software de defesa digital, proteção de nuvem e segurança cibernética.",
    expenseRatioPct: 0.47,
    aumBillionsUSD: 0.85,
    inceptionDate: "2019-06-11",
    holdingsCount: 52,
    topHoldingsConcentrationPct: 24.8,
    topHoldings: [
      { symbol: "CRWD", name: "CrowdStrike Holdings", weightPct: 5.2 },
      { symbol: "PANW", name: "Palo Alto Networks", weightPct: 4.9 },
      { symbol: "FTNT", name: "Fortinet Inc.", weightPct: 4.8 },
      { symbol: "NET", name: "Cloudflare Inc.", weightPct: 4.5 },
      { symbol: "ZS", name: "Zscaler Inc.", weightPct: 4.2 },
    ],
  },
  {
    ticker: "XLK",
    name: "Technology Select Sector SPDR Fund",
    category: "TECH_SEMIS",
    theme: "Setor de Tecnologia Amplo",
    description: "Representa 100% o setor de tecnologia dentro do índice S&P 500.",
    expenseRatioPct: 0.09,
    aumBillionsUSD: 72.3,
    inceptionDate: "1998-12-16",
    holdingsCount: 67,
    topHoldingsConcentrationPct: 42.1,
    topHoldings: [
      { symbol: "MSFT", name: "Microsoft Corp.", weightPct: 20.8 },
      { symbol: "AAPL", name: "Apple Inc.", weightPct: 15.6 },
      { symbol: "NVDA", name: "NVIDIA Corp.", weightPct: 13.9 },
      { symbol: "AVGO", name: "Broadcom Inc.", weightPct: 4.8 },
      { symbol: "ACN", name: "Accenture PLC", weightPct: 2.9 },
    ],
  },
  {
    ticker: "XLF",
    name: "Financial Select Sector SPDR Fund",
    category: "FINANCIALS",
    theme: "Bancos & Serviços Financeiros",
    description: "Principais bancos comerciais, bancos de investimento e seguradoras dos EUA (JPMorgan, Berkshire).",
    expenseRatioPct: 0.09,
    aumBillionsUSD: 41.6,
    inceptionDate: "1998-12-16",
    holdingsCount: 72,
    topHoldingsConcentrationPct: 34.8,
    topHoldings: [
      { symbol: "BRK.B", name: "Berkshire Hathaway", weightPct: 13.5 },
      { symbol: "JPM", name: "JPMorgan Chase & Co.", weightPct: 9.8 },
      { symbol: "V", name: "Visa Inc.", weightPct: 7.9 },
      { symbol: "MA", name: "Mastercard Inc.", weightPct: 6.8 },
      { symbol: "BAC", name: "Bank of America", weightPct: 4.2 },
    ],
  },
  {
    ticker: "XLV",
    name: "Health Care Select Sector SPDR Fund",
    category: "HEALTHCARE",
    theme: "Saúde & Farmacêuticas",
    description: "Farmacêuticas, biotecnologia e equipamentos médicos (Eli Lilly, Johnson & Johnson).",
    expenseRatioPct: 0.09,
    aumBillionsUSD: 40.2,
    inceptionDate: "1998-12-16",
    holdingsCount: 64,
    topHoldingsConcentrationPct: 31.9,
    topHoldings: [
      { symbol: "LLY", name: "Eli Lilly & Co.", weightPct: 10.9 },
      { symbol: "UNH", name: "UnitedHealth Group", weightPct: 9.2 },
      { symbol: "JNJ", name: "Johnson & Johnson", weightPct: 6.8 },
      { symbol: "ABBV", name: "AbbVie Inc.", weightPct: 5.4 },
      { symbol: "MRK", name: "Merck & Co. Inc.", weightPct: 4.8 },
    ],
  },
  {
    ticker: "XLI",
    name: "Industrial Select Sector SPDR Fund",
    category: "INFRA_MATERIALS",
    theme: "Bens Industriais & Aeroespacial",
    description: "Empresas de maquinário pesado, aeroespacial, defesa e transporte logístico.",
    expenseRatioPct: 0.09,
    aumBillionsUSD: 19.4,
    inceptionDate: "1998-12-16",
    holdingsCount: 78,
    topHoldingsConcentrationPct: 24.1,
    topHoldings: [
      { symbol: "GE", name: "General Electric Co.", weightPct: 5.6 },
      { symbol: "CAT", name: "Caterpillar Inc.", weightPct: 4.8 },
      { symbol: "RTX", name: "RTX Corp. (Raytheon)", weightPct: 4.5 },
      { symbol: "UNP", name: "Union Pacific Corp.", weightPct: 4.2 },
      { symbol: "HON", name: "Honeywell Intl Inc.", weightPct: 3.9 },
    ],
  },
  {
    ticker: "XLB",
    name: "Materials Select Sector SPDR Fund",
    category: "INFRA_MATERIALS",
    theme: "Materiais Básicos & Químicos",
    description: "Químicos industriais, metais, embalagens e mineração primária.",
    expenseRatioPct: 0.09,
    aumBillionsUSD: 5.6,
    inceptionDate: "1998-12-16",
    holdingsCount: 28,
    topHoldingsConcentrationPct: 41.5,
    topHoldings: [
      { symbol: "LIN", name: "Linde PLC", weightPct: 18.2 },
      { symbol: "APD", name: "Air Products & Chemicals", weightPct: 6.2 },
      { symbol: "ECL", name: "Ecolab Inc.", weightPct: 5.9 },
      { symbol: "SHW", name: "Sherwin-Williams Co.", weightPct: 5.7 },
      { symbol: "NEM", name: "Newmont Corp. (Ouro)", weightPct: 5.5 },
    ],
  },
];

export function getEtfDefinition(ticker: string): ETFDefinition | undefined {
  const t = ticker.toUpperCase();
  return ETF_UNIVERSE.find((e) => e.ticker === t);
}
